### ISSUE TITLE
GitHub redirects giving 403

### ISSUE THREAD

**Issue by TheJaredWilcurt** [andresusanto/easydl#19]
**Example:**

* https://api.github.com/repos/scout-app/scout-app/zipball/v2.18.16

In a browser this URL results in downloading a 3MB ZIP file. However when using `easydl` the redirects fail and it throws an error logging 403.

**Comment by TheJaredWilcurt** [comment]
```js
const EasyDl = require('easydl');

async function downloadZip (downloadUrl) {
  const zipFilePath = 'output.zip';
  const downloadOptions = {
    existBehavior: 'overwrite',
    maxRetry: 3,
    reportInterval: 1250
  };

  return new EasyDl(downloadUrl, zipFilePath, downloadOptions)
    .on('progress', (progress) => {
      console.log({ progress });
    })
    .wait()
    .then((completed) => {
      console.log({ completed });
    })
    .catch((error) => {
      console.log(error);
    });
};

downloadZip('https://api.github.com/repos/scout-app/scout-app/zipball/v2.18.16');
```
```bat
Error: Got HTTP Response code 403
  at Object.<anonymous> (/test/node_modules/easydl/dist/request.js:130:23)
  at Generator.next (<anonymous>)
  at fulfilled (/test/node_modules/easydl/dist/request.js:24:58)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by TheJaredWilcurt** [comment]
Seems to be related to not setting a user agent.

```
Request forbidden by administrative rules. Please make sure your request has a User-Agent header (https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required). Check https://developer.github.com for other possible causes.
```

**Comment by TheJaredWilcurt** [comment]
After using https://www.npmjs.com/package/nodejs-file-downloader it revealed more error details that helped solve it.

In the example above adding this in fixed it:

```js
  const downloadOptions = {
    existBehavior: 'overwrite',
    maxRetry: 3,
    reportInterval: 1250,
    httpOptions: {
      headers:{
        'User-Agent': 'my-library-name'
      }
    }
  };
```
